apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - db
  - todo-backend
  - todo-frontend
images:
  - name: joshturan/todo-backend
    newName: joshturan/todo-backend
    newTag: "1.2"
  - name: joshturan/todo-frontend
    newName: joshturan/todo-frontend
    newTag: "1.0"
namespace: project
