apiVersion: v1
kind: Service
metadata:
  name: todo-db-svc # Must match the serviceName in your StatefulSet
  namespace: project
spec:
  clusterIP: None # Makes it Headless
  selector:
    app: todo-db # Must match the labels in your StatefulSet
  ports:
    - port: 5432
