apiVersion: v1
kind: Secret
metadata:
  name: todo-db-secret
  namespace: project
type: Opaque
stringData:
  # Using stringData is easier because you can type plain text.
  # K8s will encode it to base64 for you automatically.
  POSTGRES_PASSWORD: "mypassword"
