apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: todo-frontend
          image: joshturan/todo-frontend:1.0
          # --- NEW SECTION: Link to your ConfigMap ---
          env:
            - name: PORT
              value: "3000" # You can put this in ConfigMap too if you prefer
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: API_URL
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: DEFAULT_IMAGE_URL
