apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
spec:
  selector:
    app: todo-backend
  ports:
    - port: 2345 # Same port! No conflict.
      protocol: TCP
      targetPort: 3000 # What your Backend Node.js code listens on
